"""empty message

Revision ID: 14654be88269
Revises: 17bfc3994e64
Create Date: 2021-05-16 12:32:00.010595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14654be88269'
down_revision = '17bfc3994e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
