"""empty message

Revision ID: 17bfc3994e64
Revises: a1dc50f9f263
Create Date: 2021-05-16 12:30:24.960750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bfc3994e64'
down_revision = 'a1dc50f9f263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
