"""empty message

Revision ID: 880bbf806c23
Revises: ccea56db82e0
Create Date: 2021-05-16 11:03:23.869753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880bbf806c23'
down_revision = 'ccea56db82e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
