"""empty message

Revision ID: 338c4268a482
Revises: c7c93bbfb8d0
Create Date: 2021-04-13 12:42:45.498936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338c4268a482'
down_revision = 'c7c93bbfb8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
