from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length, EqualTo, Email


class QuestionForm(FlaskForm):
    subject = StringField('제목', validators=[DataRequired('제목은 필수입력 항목입니다.')])
    content = TextAreaField('내용', validators=[DataRequired('내용은 필수입력 항목입니다.')])


class AnswerForm(FlaskForm):
    content = TextAreaField('내용', validators=[DataRequired('내용은 필수입력 항목입니다.')])


class UserCreateForm(FlaskForm):
    username = StringField('아이디', validators=[DataRequired(), Length(min=3, max=25)])
    password1 = PasswordField('비밀번호', validators=[
        DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])
    email = EmailField('이메일', [DataRequired(), Email()])

class UserLoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])


class UserPWchangeForm(FlaskForm):
    password1 = PasswordField('비밀번호', validators=[
        DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])
    #password = PasswordField('비밀번호', validators=[DataRequired()])


class VocaCreateForm(FlaskForm):
    voca_name = StringField('단어장제목', validators=[DataRequired()])
    voca_tag = StringField('태그', validators=[DataRequired()])
    word1 = StringField('단어1', validators=[DataRequired()])
    mean1 = StringField('뜻1', validators=[DataRequired()])
    word2 = StringField('단어2')
    mean2 = StringField('뜻2')
    word3 = StringField('단어3')
    mean3 = StringField('뜻3')
    word4 = StringField('단어4')
    mean4 = StringField('뜻4')
    word5 = StringField('단어5')
    mean5 = StringField('뜻5')
    word6 = StringField('단어6')
    mean6 = StringField('뜻6')
    word7 = StringField('단어7')
    mean7 = StringField('뜻7')
    word8 = StringField('단어8')
    mean8 = StringField('뜻8')
    word9 = StringField('단어9')
    mean9 = StringField('뜻9')
    word10 = StringField('단어10')
    mean10 = StringField('뜻10')
    word11 = StringField('단어11')
    mean11 = StringField('뜻11')
    word12 = StringField('단어12')
    mean12 = StringField('뜻12')
    word13 = StringField('단어13')
    mean13 = StringField('뜻13')
    word14 = StringField('단어14')
    mean14 = StringField('뜻14')
    word15 = StringField('단어15')
    mean15 = StringField('뜻15')
    word16 = StringField('단어16')
    mean16 = StringField('뜻16')
    word17 = StringField('단어17')
    mean17 = StringField('뜻17')
    word18 = StringField('단어18')
    mean18 = StringField('뜻18')
    word19 = StringField('단어19')
    mean19 = StringField('뜻19')
    word20 = StringField('단어20')
    mean20 = StringField('뜻20')
    word21 = StringField('단어21')
    mean21 = StringField('뜻21')
    word22 = StringField('단어22')
    mean22 = StringField('뜻22')
    word23 = StringField('단어23')
    mean23 = StringField('뜻23')
    word24 = StringField('단어24')
    mean24 = StringField('뜻24')
    word25 = StringField('단어25')
    mean25 = StringField('뜻25')
    word26 = StringField('단어26')
    mean26 = StringField('뜻26')
    word27 = StringField('단어27')
    mean27 = StringField('뜻27')
    word28 = StringField('단어28')
    mean28 = StringField('뜻28')
    word29 = StringField('단어29')
    mean29 = StringField('뜻29')
    word30 = StringField('단어30')
    mean30 = StringField('뜻30')
    word31 = StringField('단어31')
    mean31 = StringField('뜻31')
    word32 = StringField('단어32')
    mean32 = StringField('뜻32')
    word33 = StringField('단어33')
    mean33 = StringField('뜻33')
    word34 = StringField('단어34')
    mean34 = StringField('뜻34')
    word35 = StringField('단어35')
    mean35 = StringField('뜻35')
    word36 = StringField('단어36')
    mean36 = StringField('뜻36')
    word37 = StringField('단어37')
    mean37 = StringField('뜻37')
    word38 = StringField('단어38')
    mean38 = StringField('뜻38')
    word39 = StringField('단어39')
    mean39 = StringField('뜻39')
    word40 = StringField('단어40')
    mean40 = StringField('뜻40')
    word41 = StringField('단어41')
    mean41 = StringField('뜻41')
    word42 = StringField('단어42')
    mean42 = StringField('뜻42')
    word43 = StringField('단어43')
    mean43 = StringField('뜻43')
    word44 = StringField('단어44')
    mean44 = StringField('뜻44')
    word45 = StringField('단어45')
    mean45 = StringField('뜻45')
    word46 = StringField('단어46')
    mean46 = StringField('뜻46')
    word47 = StringField('단어47')
    mean47 = StringField('뜻47')
    word48 = StringField('단어48')
    mean48 = StringField('뜻48')
    word49 = StringField('단어49')
    mean49 = StringField('뜻49')
    word50 = StringField('단어50')
    mean50 = StringField('뜻50')
